export { default as LoginView } from './LoginView'
export { default as RegisterView } from './RegisterView'
export { default as ForgotPasswordView } from './ForgotPasswordView'
export { default as Test } from './user_view/Test'
export { default as LandingView} from './LandingView'